export const CHANGE_CATEGORY="CHANGE_CATEGORY";
export const GET_CATEGORIES_SUCCES="GET_CATEGORIES_SUCCES";

export const GET_PRODUCTS_SUCCES="GET_PRODUCTS_SUCCES";
export const CREATE_PRODUCT_SUCCES="CREATE_PRODUCT_SUCCES"
export const UPDATE_PRODUCT_SUCCES="UPDATE_PRODUCT_SUCCES"

export const ADD_TO_CART="ADD_TO_CART";
export const REMOVE_FROM_CART="REMOVE_FROM_CART"